export const layers = [
  { n: "00", title: "Energy & Power Grid", short: "Power", color: "#d6ff5f", thesis: "AI begins with electricity. Generation, transmission, cooling and power management are becoming the physical constraint on compute growth.", explainer: "Data centers cannot run on software alone. They need reliable electricity around the clock, high-voltage connections, backup systems and cooling that removes enormous amounts of heat. As AI clusters grow, securing power can determine where—and how quickly—new capacity is built.", value: "Owners of scarce generation, grid equipment and mission-critical cooling can benefit before a model produces a single token.", risk: "Slow permitting, regulated returns, falling demand or rapid efficiency gains could limit the upside.", includes: ["Generation", "Grid equipment", "Cooling", "Power management"], signals: ["Data-center power demand is reshaping utility planning", "Grid interconnection queues remain a deployment constraint"], companies: ["VRT", "GEV", "ETN"] },
  { n: "01", title: "Silicon & Manufacturing", short: "Silicon", color: "#78e7ff", thesis: "The hardest-to-replicate tools and processes sit deep inside the semiconductor supply chain, where technical leadership compounds over decades.", explainer: "Every AI chip begins as a design and becomes physical through an extraordinarily complex manufacturing chain. Specialized design software, lithography machines, foundries, process-control tools and advanced packaging must all work together at atomic-scale precision.", value: "The strongest economics often sit with suppliers whose technology is required at every leading-edge node and cannot be duplicated quickly.", risk: "Semiconductor cycles, export controls, customer concentration and manufacturing delays remain central risks.", includes: ["Lithography", "Foundries", "EDA software", "Process control"], signals: ["Leading-edge nodes require rising capital intensity", "Advanced packaging is now a strategic bottleneck"], companies: ["ASML", "TSM", "CDNS"] },
  { n: "02", title: "Compute & Networking", short: "Compute", color: "#a894ff", thesis: "Accelerators, memory and high-speed networks turn silicon into usable AI capacity. Performance-per-watt is the key economic metric.", explainer: "Training and serving modern models requires thousands of accelerators to behave like one machine. GPUs perform the calculations, high-bandwidth memory keeps data close, and networking moves information between chips without creating expensive idle time.", value: "Platforms combining chips, networking and software can capture more value because customers buy a working system—not isolated hardware.", risk: "Custom chips, changing model architectures, supply normalization and more efficient inference could weaken pricing power.", includes: ["Accelerators", "Networking", "Memory", "Interconnect"], signals: ["Cluster scale is moving from thousands to hundreds of thousands of chips", "Networking is taking a larger share of AI infrastructure spend"], companies: ["NVDA", "AVGO", "ANET"] },
  { n: "03", title: "Cloud & Data Centers", short: "Cloud", color: "#ffb86b", thesis: "Hyperscalers aggregate infrastructure, distribution and developer ecosystems—turning massive capital expenditure into rented intelligence.", explainer: "Most companies will not build their own AI supercomputer. Cloud platforms finance the infrastructure, operate it globally and rent access through developer-friendly services. Data-center operators provide the specialized real estate, connectivity and power underneath them.", value: "Scale lowers unit costs, while enterprise relationships and developer ecosystems make the cloud a powerful distribution layer for AI.", risk: "Heavy capital expenditure, capacity shortages, price competition and workload portability can pressure returns.", includes: ["Hyperscale cloud", "Colocation", "Data platforms", "AI services"], signals: ["Cloud providers are accelerating AI infrastructure investment", "Capacity access is becoming a competitive advantage"], companies: ["MSFT", "AMZN", "GOOGL"] },
  { n: "04", title: "Foundation Models", short: "Models", color: "#ff7ab6", thesis: "Foundation models convert compute and data into general intelligence. Distribution, proprietary data and inference economics may matter more than leaderboard position.", explainer: "Foundation models are general-purpose systems trained on broad datasets and adapted to many tasks. They provide the language, reasoning, image and multimodal capabilities that developers access through APIs or open model weights.", value: "Long-term advantage may come from distribution, proprietary feedback data, developer adoption and better output at lower inference cost.", risk: "Rapid commoditization, open-source competition, regulation and weak switching costs could move profits to adjacent layers.", includes: ["Language models", "Multimodal models", "Model tooling", "Inference"], signals: ["Model performance gaps continue to narrow", "Inference cost and distribution increasingly shape adoption"], companies: ["GOOGL", "META", "MSFT"] },
  { n: "05", title: "Applications & Agents", short: "Apps", color: "#6fffc5", thesis: "The application layer translates model capability into measurable workflows. Winners need proprietary context, trusted distribution and high switching costs.", explainer: "Applications combine models with company data, interfaces and workflow logic. Agents go further: they can plan a task, use tools and complete multiple actions with limited supervision. This is where AI becomes visible to the end customer.", value: "Applications capture durable value when they own the workflow, hold trusted data and deliver measurable outcomes—not merely add a chatbot.", risk: "Features can be copied, model providers may move up the stack, and uncertain ROI can slow enterprise adoption.", includes: ["Enterprise agents", "Vertical software", "Developer tools", "Consumer AI"], signals: ["Enterprise buyers are shifting from pilots toward workflow deployment", "Incumbents are embedding agents into systems of record"], companies: ["PLTR", "NOW", "CRM"] },
];
export const companies: Record<string, any> = {
  ASML: { name: "ASML Holding", ticker: "ASML", layer: "01 · Silicon & Manufacturing", price: "€1,146.20", move: "+18.4% YTD", moat: "Near-monopoly", score: 96, summary: "The sole commercial supplier of EUV lithography systems required for the world's most advanced logic chips.", metrics: [["Market cap", "€458B"], ["Forward P/E", "41.2×"], ["Revenue growth", "16.8%"], ["Gross margin", "52.1%"], ["FCF margin", "29.4%"], ["ROIC", "34.7%"]], thesis: ["Decades of accumulated optics, mechatronics and supplier know-how", "Deep co-development with the world's leading chipmakers", "Next-generation High-NA systems extend the technology roadmap"], news: [["Capacity", "High-NA adoption moves from evaluation toward production planning"], ["Demand", "AI accelerators support leading-edge foundry equipment demand"], ["Risk", "Export restrictions remain the most material policy variable"]], scenarios: [["Bear", "€38B", "31%", "Delayed fab spending"], ["Base", "€43B", "34%", "Roadmap executes"], ["Bull", "€48B", "37%", "High-NA ramps faster"]] },
  NVDA: { name: "NVIDIA", ticker: "NVDA", layer: "02 · Compute & Networking", price: "$178.42", move: "+24.7% YTD", moat: "Platform ecosystem", score: 91, summary: "The reference platform for accelerated computing, combining leading chips, networking and a deeply embedded software ecosystem.", metrics: [["Market cap", "$4.35T"], ["Forward P/E", "33.6×"], ["Revenue growth", "48.2%"], ["Gross margin", "73.5%"], ["FCF margin", "51.8%"], ["ROIC", "78.4%"]], thesis: ["CUDA creates powerful developer and workload switching costs", "Full-stack systems improve time-to-deployment for customers", "Scale funds an aggressive annual product cadence"], news: [["Product", "Next architecture enters volume deployment with cloud partners"], ["Network", "Ethernet and InfiniBand expand the addressable cluster stack"], ["Risk", "Customer concentration and custom silicon deserve close monitoring"]], scenarios: [["Bear", "$244B", "50%", "Capex digestion"], ["Base", "$281B", "55%", "Demand stays broad"], ["Bull", "$325B", "58%", "Sovereign AI accelerates"]] },
  MSFT: { name: "Microsoft", ticker: "MSFT", layer: "03 · Cloud & Data Centers", price: "$564.18", move: "+13.9% YTD", moat: "Distribution + switching costs", score: 89, summary: "A uniquely distributed AI platform spanning cloud infrastructure, developer tooling and enterprise workflows.", metrics: [["Market cap", "$4.19T"], ["Forward P/E", "31.4×"], ["Revenue growth", "15.6%"], ["Gross margin", "69.2%"], ["FCF margin", "31.1%"], ["ROIC", "27.8%"]], thesis: ["Azure, GitHub and Microsoft 365 create unmatched enterprise distribution", "Large installed base lowers the cost of AI product adoption", "Infrastructure and applications reinforce each other"], news: [["Cloud", "AI services remain a major contributor to Azure growth"], ["Capacity", "Infrastructure investment expands available AI capacity"], ["Risk", "Returns on elevated capital expenditure require monitoring"]], scenarios: [["Bear", "$345B", "36%", "AI monetization lags"], ["Base", "$372B", "38%", "Copilot adoption builds"], ["Bull", "$405B", "40%", "Agents lift ARPU"]] },
};
export const allStocks = [["ASML", "ASML", "Near-monopoly", "96"], ["NVIDIA", "NVDA", "Platform moat", "91"], ["Microsoft", "MSFT", "Distribution", "89"], ["TSMC", "TSM", "Scale + process", "94"], ["Broadcom", "AVGO", "Custom silicon", "88"], ["Arista", "ANET", "Network OS", "84"]];

const profile=(name:string,ticker:string,layer:string,moat:string,score:number,summary:string)=>({name,ticker,layer,price:"—",move:"Analysis profile",moat,score,summary,metrics:[["Market cap","Connect data"],["Forward P/E","Connect data"],["Revenue growth","Connect data"],["Gross margin","Connect data"],["FCF margin","Connect data"],["ROIC","Connect data"]],thesis:[`${moat} is the central source of defensibility`,"Positioned at a difficult-to-replace point in the AI value chain","Scale and customer integration reinforce the competitive position"],news:[["Thesis","Monitor whether the company is strengthening its position"],["Demand","Track end-market growth and customer investment"],["Risk","Watch competition, valuation and execution"]],scenarios:[["Bear","TBD","TBD","Moat weakens"],["Base","TBD","TBD","Current position holds"],["Bull","TBD","TBD","AI demand accelerates"]]});
Object.assign(companies,{
  VRT:profile("Vertiv","VRT","00 · Energy & Power Grid","Thermal infrastructure",84,"Critical power and cooling systems designed for high-density data-center environments."),
  GEV:profile("GE Vernova","GEV","00 · Energy & Power Grid","Installed base + scale",82,"Generation and grid equipment supporting the expansion and modernization of electricity infrastructure."),
  ETN:profile("Eaton","ETN","00 · Energy & Power Grid","Electrical distribution",86,"Mission-critical electrical equipment connecting new power demand to data centers and the grid."),
  TSM:profile("TSMC","TSM","01 · Silicon & Manufacturing","Process leadership",94,"The leading independent foundry manufacturing many of the world's most advanced AI chips."),
  CDNS:profile("Cadence Design Systems","CDNS","01 · Silicon & Manufacturing","EDA duopoly",90,"Essential software and intellectual property used to design increasingly complex semiconductors."),
  AVGO:profile("Broadcom","AVGO","02 · Compute & Networking","Custom silicon + connectivity",88,"Custom accelerators and networking silicon powering hyperscale AI infrastructure."),
  ANET:profile("Arista Networks","ANET","02 · Compute & Networking","Network operating system",84,"High-speed networking platforms connecting large cloud and AI computing clusters."),
  AMZN:profile("Amazon","AMZN","03 · Cloud & Data Centers","Cloud scale + distribution",88,"AWS combines global infrastructure, proprietary chips and enterprise AI services."),
  GOOGL:profile("Alphabet","GOOGL","03–04 · Cloud & Foundation Models","Data + distribution",89,"A full-stack AI company spanning infrastructure, frontier models, search and global consumer distribution."),
  META:profile("Meta Platforms","META","04 · Foundation Models","Data + consumer network",85,"Open foundation models supported by a vast consumer distribution and advertising engine."),
  PLTR:profile("Palantir Technologies","PLTR","05 · Applications & Agents","Ontology + workflow",83,"An operating layer connecting AI models to governed enterprise data and operational decisions."),
  NOW:profile("ServiceNow","NOW","05 · Applications & Agents","Workflow switching costs",87,"A system of action embedding AI agents into deeply integrated enterprise workflows."),
  CRM:profile("Salesforce","CRM","05 · Applications & Agents","Customer data + distribution",84,"A large enterprise application platform bringing agents into sales and service workflows.")
});

const companyInfo:Record<string,{business:string,role:string,customers:string,competitors:string,watch:string,development:string}>={
  VRT:{business:"Designs power, cooling and monitoring systems for data centers and communications networks.",role:"Keeps high-density AI racks powered and within safe thermal limits.",customers:"Hyperscalers, colocation providers, telecom operators and enterprises.",competitors:"Schneider Electric, Eaton and specialized cooling providers.",watch:"Liquid-cooling adoption, capacity expansion and backlog conversion.",development:"Vertiv raised its 2026 outlook after strong demand for AI-ready power and cooling infrastructure."},
  GEV:{business:"Builds gas turbines, grid equipment, wind systems and electrification software.",role:"Adds generation and transmission capacity needed to serve large new AI loads.",customers:"Utilities, governments, developers and industrial operators.",competitors:"Siemens Energy, Mitsubishi Heavy Industries and Hitachi Energy.",watch:"Gas-turbine orders, grid backlog, execution and service margins.",development:"Data-center electricity demand has become a larger driver of generation and grid-equipment orders."},
  ETN:{business:"Produces electrical distribution, protection and power-management equipment.",role:"Connects utility power to data-center campuses and distributes it safely within facilities.",customers:"Data centers, utilities, commercial buildings and industrial companies.",competitors:"Schneider Electric, ABB and Siemens.",watch:"Data-center order growth, capacity additions and electrical segment margins.",development:"Eaton continues to expand capacity as power availability becomes a constraint for AI infrastructure."},
  ASML:{business:"Builds lithography systems used to print microscopic chip patterns onto silicon wafers.",role:"Its EUV machines are indispensable for manufacturing the most advanced AI processors.",customers:"TSMC, Samsung and Intel.",competitors:"No commercial peer in EUV; Nikon and Canon compete in older lithography technologies.",watch:"High-NA adoption, leading-edge fab spending and export restrictions.",development:"ASML raised its 2026 sales outlook as AI demand supported investment in leading-edge manufacturing."},
  TSM:{business:"Manufactures chips designed by fabless semiconductor companies.",role:"Produces the leading GPUs, custom accelerators and networking chips powering AI systems.",customers:"NVIDIA, Apple, AMD, Broadcom and other chip designers.",competitors:"Samsung Foundry and Intel Foundry.",watch:"2nm ramp, advanced-packaging capacity, Arizona execution and geopolitical risk.",development:"AI accelerator demand and advanced-node utilization remain central to TSMC's growth and capacity plans."},
  CDNS:{business:"Provides electronic-design automation software and reusable semiconductor intellectual property.",role:"Enables engineers to design and verify increasingly complex AI chips and systems.",customers:"Semiconductor designers, systems companies and manufacturers.",competitors:"Synopsys and Siemens EDA.",watch:"AI-assisted design adoption, IP growth and semiconductor R&D spending.",development:"Cadence is embedding generative AI deeper into chip-design workflows while expanding system-level analysis."},
  NVDA:{business:"Designs accelerated-computing platforms spanning GPUs, networking, systems and software.",role:"Provides the dominant platform used to train and serve advanced AI models.",customers:"Cloud providers, model laboratories, governments and enterprises.",competitors:"AMD, custom hyperscaler chips and specialized accelerator startups.",watch:"Platform transitions, supply, customer concentration and inference competition.",development:"NVIDIA agreed to acquire Hugging Face, extending its reach into open models and developer distribution."},
  AVGO:{business:"Designs networking and custom silicon while operating a large infrastructure-software portfolio.",role:"Helps hyperscalers build custom AI accelerators and connect enormous compute clusters.",customers:"Large cloud platforms, network-equipment companies and enterprises.",competitors:"NVIDIA, Marvell and internal hyperscaler design teams.",watch:"Custom accelerator programs, networking content and customer concentration.",development:"Custom AI silicon and high-speed networking have become the main growth engines within Broadcom's semiconductor business."},
  ANET:{business:"Builds high-speed switches and a common network operating system for cloud-scale environments.",role:"Connects AI accelerators using scalable Ethernet-based networks.",customers:"Microsoft, Meta and other cloud and enterprise data-center operators.",competitors:"Cisco, NVIDIA and white-box networking vendors.",watch:"AI networking revenue, customer concentration and Ethernet adoption in back-end clusters.",development:"Arista is expanding its AI networking portfolio as hyperscalers build larger Ethernet-based clusters."},
  MSFT:{business:"Operates Azure, Microsoft 365, GitHub, Windows and a broad enterprise-software ecosystem.",role:"Distributes AI through cloud infrastructure, developer tools and everyday enterprise workflows.",customers:"Organizations, developers, governments and consumers worldwide.",competitors:"Amazon, Google, Oracle and specialized software vendors.",watch:"Azure growth, Copilot adoption, capacity constraints and returns on capital expenditure.",development:"Microsoft is reorganizing financial reporting around “Agents and Infra” and will disclose Azure revenue more directly."},
  AMZN:{business:"Operates AWS, ecommerce marketplaces, advertising and logistics infrastructure.",role:"AWS rents AI compute, offers proprietary Trainium chips and distributes foundation-model services.",customers:"Startups, enterprises, governments, sellers and consumers.",competitors:"Microsoft Azure, Google Cloud and Oracle Cloud.",watch:"AWS growth, Trainium adoption, AI capacity and free-cash-flow pressure from investment.",development:"AWS continues to expand AI infrastructure and its strategic relationship with Anthropic while investing heavily in Trainium."},
  GOOGL:{business:"Operates Search, YouTube, Google Cloud and a portfolio of AI models and consumer products.",role:"Spans the full stack from custom TPUs and cloud infrastructure to Gemini models and global distribution.",customers:"Advertisers, consumers, developers and enterprises.",competitors:"Microsoft, Amazon, Meta, OpenAI and specialist AI services.",watch:"Gemini adoption, Search monetization, cloud margins, regulation and AI capital intensity.",development:"Alphabet is increasing AI infrastructure investment while integrating Gemini across Search, Cloud and Workspace."},
  META:{business:"Operates social platforms and an advertising engine funded by massive recommendation systems.",role:"Develops Llama models and distributes AI assistants across billions of consumer accounts.",customers:"Users, creators, advertisers and business messaging customers.",competitors:"Google, TikTok, OpenAI and other consumer platforms.",watch:"Llama strategy, advertising returns, infrastructure spending and regulation.",development:"Meta continues to invest heavily in frontier models and compute while using AI to improve advertising and engagement."},
  PLTR:{business:"Provides software that connects complex organizational data to operational decisions.",role:"Its ontology and deployment model help enterprises apply AI to governed, real-world workflows.",customers:"Governments, defense organizations and large commercial enterprises.",competitors:"Cloud data platforms, systems integrators and internally built solutions.",watch:"Commercial adoption, deal concentration, margins and durability of AI Platform demand.",development:"Palantir raised its 2026 revenue expectations as demand for its AI Platform accelerated."},
  NOW:{business:"Runs a cloud platform for automating enterprise technology, employee and customer workflows.",role:"Provides the governance and workflow layer through which enterprise agents can take action.",customers:"Large enterprises and public-sector organizations.",competitors:"Salesforce, Microsoft, Atlassian and specialist workflow tools.",watch:"AI monetization, large deals, platform consolidation and execution.",development:"ServiceNow introduced Project Arc and expanded agent governance from employee devices to AI data centers."},
  CRM:{business:"Provides customer-relationship, service, marketing, data and collaboration software.",role:"Uses trusted customer data and workflow distribution to deploy enterprise agents through Agentforce.",customers:"Businesses across sales, service, marketing and commerce.",competitors:"Microsoft, ServiceNow, HubSpot, Oracle and Adobe.",watch:"Agentforce adoption, Data Cloud growth, seat pressure and margin discipline.",development:"Salesforce and Anthropic announced Claudeforce, bringing Claude models into Salesforce's AI CRM ecosystem."}
};
for(const [ticker,info] of Object.entries(companyInfo)) Object.assign(companies[ticker],info);
const moatAnalysis:Record<string,{thesis:string[],moatDurability:string[],moatSignals:string[]}>= {
  VRT:{thesis:["Deep expertise in mission-critical power and thermal management","Installed equipment creates recurring service relationships","A broad portfolio lets customers source integrated infrastructure"],moatDurability:["High-density AI racks make thermal engineering more specialized","Qualification and reliability requirements discourage supplier changes","Manufacturing capacity and global service coverage take years to build"],moatSignals:["Liquid-cooling share of new deployments","Backlog conversion without margin dilution","Service revenue growing with the installed base"]},
  GEV:{thesis:["A vast installed turbine base anchors long-lived service revenue","Utility-grade equipment requires trusted engineering and certification","Scarce manufacturing slots support pricing and backlog visibility"],moatDurability:["Gas turbines and grid hardware operate for decades","Service knowledge compounds across the installed fleet","Permitting, qualification and capital intensity limit new entrants"],moatSignals:["Gas-turbine slot availability and new orders","Grid backlog growth and delivery execution","Service margins and long-term agreement attachment"]},
  ETN:{thesis:["Electrical products are specified into critical facility designs","A broad portfolio spans power distribution, protection and control","Channel reach and field support strengthen customer preference"],moatDurability:["Changing qualified components can trigger costly redesigns","Installed equipment expands aftermarket and replacement demand","Scale supports capacity investment and a wide product catalogue"],moatSignals:["Data-center orders relative to added capacity","Lead times and pricing in electrical products","Share gains in high-voltage and power-quality systems"]},
  ASML:{thesis:["The only commercial source of EUV lithography systems","Decades of optics, mechatronics and process knowledge are inseparable","Roadmap co-development embeds ASML inside leading fabs"],moatDurability:["EUV depends on a uniquely capable supplier network led by Zeiss","Customer process recipes deepen with each installed generation","High-NA extends the technology path and raises replication costs"],moatSignals:["High-NA orders and customer production milestones","EUV productivity improvements in the field","R&D intensity and continuity across the supplier ecosystem"]},
  TSM:{thesis:["Leading yields turn advanced process technology into dependable volume","A neutral foundry model earns trust across competing chip designers","Scale spreads enormous fabrication and packaging investment"],moatDurability:["Process learning compounds across customers and product designs","Advanced packaging links leading-edge wafers to complete AI systems","A broad technology roadmap makes switching foundries costly"],moatSignals:["2nm yield and volume-ramp progress","Advanced-packaging capacity and utilization","Leading customers retaining TSMC for next-generation designs"]},
  CDNS:{thesis:["An EDA duopoly sits at the center of chip-design workflows","Software is deeply integrated into years-long design and verification cycles","Design IP and system analysis broaden the value captured per project"],moatDurability:["Validated tool flows make switching risky near tape-out","Accumulated design data improves automation and customer productivity","Semiconductor complexity raises the need for trusted verification"],moatSignals:["Renewal strength and expansion within major accounts","Growth in reusable IP and system-design products","Adoption of AI-assisted design across production workflows"]},
  NVDA:{thesis:["CUDA is the default software environment for accelerated computing","Chips, networking and systems form an integrated platform","Developer adoption and scale reinforce each new architecture"],moatDurability:["A vast library and tooling ecosystem lowers time to deployment","Annual hardware and software releases raise the pace competitors must match","Installed infrastructure makes compatibility economically valuable"],moatSignals:["CUDA usage across new model and inference workloads","Networking and systems growing alongside accelerators","Customer adoption through major platform transitions"]},
  AVGO:{thesis:["Deep co-design relationships secure custom hyperscaler programs","Networking IP connects increasingly large AI clusters","A broad semiconductor portfolio shares engineering and customer access"],moatDurability:["Custom accelerators require multi-year roadmaps and close collaboration","High-speed connectivity expertise is difficult to reproduce quickly","Winning one generation improves credibility for the next design cycle"],moatSignals:["Number and scale of custom accelerator programs","Networking content per AI cluster","Program continuity across customer silicon generations"]},
  ANET:{thesis:["EOS provides one operating model across the network","Cloud-scale reliability and automation are proven in demanding environments","Long customer relationships influence product roadmaps"],moatDurability:["Operational tools and workflows create meaningful switching costs","A single software image compounds engineering efficiency","Ethernet leadership expands from front-end into AI back-end networks"],moatSignals:["AI back-end wins using Ethernet","Customer diversification beyond the largest cloud accounts","Software adoption and retention through hardware upgrades"]},
  MSFT:{thesis:["Azure, Microsoft 365 and GitHub provide unmatched enterprise distribution","Identity, data and workflows connect infrastructure to applications","Existing contracts lower the friction of adopting new AI products"],moatDurability:["Systems of record create high organizational switching costs","The product suite supplies proprietary context for useful agents","Infrastructure and application demand reinforce one another"],moatSignals:["Copilot expansion from trials into paid deployment","Azure AI demand alongside capacity additions","Cross-product usage of agents, data and identity services"]},
  AMZN:{thesis:["AWS scale and service breadth make it a default enterprise platform","Developer familiarity and architecture create workload switching costs","Custom silicon improves control over cost and capacity"],moatDurability:["A huge installed base supports constant infrastructure investment","Marketplace, partners and APIs deepen the surrounding ecosystem","Operational scale broadens regional capacity and service availability"],moatSignals:["AWS workload growth and customer migrations","Trainium adoption in production AI workloads","AI service usage beyond raw compute rental"]},
  GOOGL:{thesis:["Search, YouTube and Android provide global distribution","TPUs, cloud infrastructure and Gemini create a full-stack platform","Proprietary interaction data improves products and monetization"],moatDurability:["AI can be embedded into products already used every day","Research depth and custom silicon lower dependence on outside platforms","Advertiser demand funds continual model and infrastructure investment"],moatSignals:["Gemini engagement across Search and Workspace","Google Cloud AI customer growth and profitability","Search usage and monetization as answers become more generative"]},
  META:{thesis:["Billions of users create rare consumer distribution","Recommendation and advertising systems generate powerful feedback loops","Open models can attract developers into Meta's ecosystem"],moatDurability:["Social graphs and creator networks are hard to recreate","AI improvements can be monetized through the existing ad engine","Infrastructure scale supports frontier-model development"],moatSignals:["Engagement gains attributable to AI recommendations","Advertiser returns from AI creative and targeting tools","Llama developer adoption and ecosystem contribution"]},
  PLTR:{thesis:["Its ontology connects models to governed operational data","Deployments become embedded in high-value decisions and workflows","Longstanding government trust supports access to sensitive missions"],moatDurability:["Customer-specific data models accumulate institutional knowledge","Replacing operational workflows carries execution and security risk","Reusable deployment expertise shortens time to value"],moatSignals:["Expansion from pilots into production workflows","Net retention and deal growth within existing customers","Repeatable deployment speed without heavy services growth"]},
  NOW:{thesis:["ServiceNow owns workflows that coordinate work across departments","Its platform connects enterprise data, approvals and action","A large installed base gives agents immediate distribution"],moatDurability:["Deep workflow customization raises switching costs","A shared data model lets new modules reinforce the platform","Governance and permissions make enterprise automation defensible"],moatSignals:["AI products expanding contract value at renewal","Customers consolidating more workflows on the platform","Agent actions completed inside governed production processes"]},
  CRM:{thesis:["Customer data and workflows make Salesforce a system of record","A large sales channel distributes new products into existing accounts","AppExchange and integrations extend the platform's reach"],moatDurability:["Years of customer history and customization resist migration","Data Cloud can unify context across sales, service and marketing","Agents become stickier when embedded in core revenue workflows"],moatSignals:["Agentforce moving from trials to paid usage","Data Cloud adoption across the installed base","Retention and expansion despite pressure on per-seat software"]}
};
for(const [ticker,analysis] of Object.entries(moatAnalysis)) Object.assign(companies[ticker],analysis);
const moatWhy:Record<string,string[]>= {
  VRT:["Failure is extremely costly, so customers favour suppliers with proven engineering and uptime.","Servicing installed systems creates recurring revenue and keeps Vertiv close to future expansion plans.","An integrated offering reduces design complexity and the number of vendors customers must coordinate.","Higher rack densities increase cooling difficulty, making specialist knowledge more valuable.","Once equipment is tested and approved, changing suppliers introduces reliability and redesign risk.","New factories, trained technicians and worldwide support coverage cannot be replicated quickly."],
  GEV:["A large operating fleet produces decades of service work and proprietary performance knowledge.","Utilities prioritise reliability and regulatory acceptance, favouring suppliers with a long operating record.","Limited production capacity lets established manufacturers secure long backlogs and favourable contract terms.","Long asset lives turn each new installation into a durable customer and service relationship.","Fleet data improves maintenance, reliability and future designs in a way newcomers cannot easily match.","The cost, certification and time required to build utility-grade equipment restrict competition."],
  ETN:["Being designed into a facility early makes replacement costly once construction and approvals begin.","Customers can standardise on one trusted supplier across many critical electrical functions.","Distributor access and local engineering support make Eaton easier to specify, obtain and maintain.","Substituting approved components may require new testing, documentation and engineering work.","A growing installed base supports recurring replacement, upgrade and service demand.","Scale funds additional capacity and keeps a wider product range available than smaller rivals."],
  ASML:["Without ASML's EUV systems, chipmakers cannot economically manufacture the most advanced designs.","The machine combines thousands of interdependent breakthroughs that no single competitor can easily reproduce.","Joint roadmap planning makes ASML essential to customers years before a new process enters production.","Its specialist suppliers contribute unique components built through decades of close collaboration.","Fab processes are tuned around ASML tools, so replacing them would disrupt yields and production.","High-NA improves future chip scaling while increasing the technical and financial barrier to entry."],
  TSM:["High yields lower customers' cost per working chip and reduce the risk of product launches.","Customers can share sensitive designs without empowering a competing chip-product business.","Its volume allows enormous R&D and factory costs to be spread across many customers.","Every production run adds learning that improves yields and makes the next process ramp more dependable.","Packaging capacity is increasingly essential for combining processors and memory into complete AI systems.","Moving a chip design requires costly revalidation, new tooling and months of engineering work."],
  CDNS:["Only a few vendors can provide the complete, trusted toolchain needed for advanced chip design.","Engineers build processes and expertise around these tools, making mid-project changes unusually risky.","Selling design IP and system analysis deepens customer dependence beyond the core software suite.","A failed verification can delay a chip by months, so proven workflows outweigh small price differences.","More design activity produces data that can improve automation and engineering productivity.","As chips become more complex, customers need broader simulation and verification rather than fewer tools."],
  NVDA:["Developers can reuse familiar tools and libraries instead of rewriting workloads for another platform.","Customers receive a tested system, reducing the time and technical risk of assembling components themselves.","A larger user base attracts more developers, software support and optimisation for each new generation.","Years of libraries, documentation and trained developers make CUDA more than a hardware feature.","Fast product cycles force competitors to match improvements across chips, networking and software simultaneously.","Compatibility with existing code and infrastructure makes staying on the platform economically attractive."],
  AVGO:["Designing a custom accelerator requires years of collaboration, making established partnerships difficult to displace.","Proven networking technology is critical because slow data movement can waste expensive compute capacity.","Shared engineering and customer relationships allow Broadcom to sell more content into each platform.","Successful first-generation programs create trust and technical knowledge for later, larger deployments.","Advanced connectivity depends on specialised intellectual property developed over many product cycles.","Each completed program improves Broadcom's credibility when customers select partners for the next generation."],
  ANET:["A consistent operating system simplifies automation and management across thousands of network devices.","Customers trust Arista in environments where outages can idle very expensive cloud and AI infrastructure.","Close collaboration with hyperscalers helps products evolve around real operating requirements.","Monitoring, automation and staff knowledge built around EOS make a platform change operationally disruptive.","Maintaining one software foundation lets features and reliability improvements reach the whole portfolio.","Success in AI back-end networks expands Arista's role without abandoning its established Ethernet strength."],
  MSFT:["Microsoft can place AI directly inside tools that enterprises and developers already use daily.","Shared identity, permissions and data make its AI services easier to deploy securely across organisations.","Existing procurement relationships reduce the time and effort needed to adopt another Microsoft product.","Migrating core productivity and cloud systems would require substantial retraining, integration and operational change.","Workplace data gives agents the context needed to perform useful tasks rather than only answer questions.","Demand for applications drives Azure usage, while Azure capabilities make the applications more valuable."],
  AMZN:["Customers can build almost any workload without coordinating infrastructure across multiple providers.","Applications built around AWS services and APIs become expensive and technically difficult to migrate.","Purpose-built chips can improve cost, availability and performance for common AI workloads.","A very large customer base justifies continuous investment in regions, capacity and new services.","Partners and third-party software reduce implementation effort and make AWS more useful to customers.","Global operating experience enables AWS to provide capacity and reliability that smaller providers struggle to match."],
  GOOGL:["Google can introduce AI to billions of users without paying another platform for distribution.","Owning chips, infrastructure and models allows optimisation across the entire cost and performance stack.","User interactions provide feedback that improves product relevance and advertising effectiveness.","Embedding Gemini into established products makes adoption easier than asking users to learn a separate service.","Longstanding research teams and TPUs reduce dependence on external models and general-purpose hardware.","Advertising cash flow can fund the sustained model and infrastructure investment required to remain competitive."],
  META:["Meta can distribute assistants and AI features instantly across its global family of apps.","More engagement produces feedback that improves recommendations, which can create still more engagement.","Open access encourages developers to optimise and build around Llama rather than a competing model family.","Users, creators and relationships form networks that remain valuable even when individual features are copied.","AI improvements can translate quickly into better ad targeting, creative tools and advertiser returns.","Large infrastructure spending supports model development at a scale available to very few companies."],
  PLTR:["The ontology translates fragmented company data into objects and relationships that models can use safely.","Once software guides operational decisions, removal becomes more disruptive than replacing a reporting tool.","Security credentials and mission experience are important barriers in sensitive government environments.","Customer-specific models capture processes and institutional knowledge that accumulate throughout a deployment.","Replacing the platform can interrupt critical operations and require complex security reapproval.","Experience across deployments allows Palantir to solve similar problems faster for the next customer."],
  NOW:["Owning the workflow lets ServiceNow determine how requests, approvals and actions move through a company.","A common platform connects otherwise separate departments and reduces integration complexity.","Existing customers can adopt agents inside familiar processes without introducing a new operating layer.","Years of configuration and integrations make moving workflows to another platform expensive and risky.","Each added module contributes more context and makes the overall platform harder to replace.","Central governance makes automated actions safer, which is essential for enterprise adoption of agents."],
  CRM:["Salesforce sits close to revenue-generating work and stores information employees need every day.","Its salesforce can introduce new AI and data products through relationships with existing enterprise buyers.","Partners, applications and integrations make the platform useful beyond Salesforce's own products.","Historical customer data and customised processes are costly to move without disrupting commercial teams.","Unifying fragmented information gives agents better context across the entire customer relationship.","Agents become more valuable and defensible when they can act directly inside core sales and service processes."]
};
for(const [ticker,why] of Object.entries(moatWhy)) companies[ticker].moatWhy=why;
const moatContext:Record<string,string[]>= {
  VRT:["These operators cannot tolerate downtime, so proven reliability and service coverage heavily influence purchasing.","Competition is credible, but Vertiv differentiates through data-center specialisation and an integrated global offering.","Rising adoption would confirm that Vertiv remains central as rack densities increase.","Healthy conversion shows demand is real and that pricing power survives rapid capacity expansion.","Faster service growth would make revenue more recurring and deepen relationships with installed customers."],
  GEV:["Utilities and developers make multi-decade asset decisions, placing a premium on bankability and lifecycle support.","Peers have comparable engineering depth, making execution, available production slots and fleet economics decisive.","More orders would show that power scarcity is translating into durable equipment demand.","Backlog growth only strengthens the moat if GE Vernova can deliver reliably and profitably.","Higher service margins would prove the installed fleet is producing valuable recurring economics."],
  ETN:["Electrical systems are selected early in a project and must meet strict safety and reliability requirements.","Large rivals offer similar breadth, so product availability, channel access and specification wins determine share.","Order growth ahead of capacity would indicate customers continue to specify Eaton in new facilities.","Longer lead times and stable pricing suggest supply remains scarce and customer demand is resilient.","Share gains would show Eaton is expanding its role in the most technically demanding parts of power distribution."],
  ASML:["Only a handful of advanced chipmakers buy EUV, but each depends on ASML for its technology roadmap.","Older lithography alternatives cannot replace EUV at leading nodes, leaving ASML without a direct commercial peer.","Production adoption would validate both customer dependence and the next phase of ASML's roadmap.","Higher field productivity increases customer output and makes every installed system more economically valuable.","Sustained investment protects the knowledge gap that makes the monopoly difficult to challenge."],
  TSM:["Leading chip designers choose TSMC because yield, scale and dependable execution directly affect their own launches.","Samsung and Intel can compete technologically, but must match TSMC's yields, capacity and trusted foundry model.","A smooth ramp would confirm that process leadership is continuing at the next major node.","Capacity expansion shows whether TSMC can capture demand beyond wafer fabrication itself.","Repeated customer commitments indicate that rivals are not closing the gap enough to trigger switching."],
  CDNS:["Chip designers rely on these tools throughout development, making accuracy and workflow continuity mission-critical.","Synopsys is the closest peer; competition is largely between two entrenched ecosystems rather than new entrants.","Strong renewals show customers still view Cadence as embedded infrastructure rather than discretionary software.","Growth would demonstrate that Cadence is capturing more value from each increasingly complex design.","Production use matters more than pilots because it proves AI features improve real engineering economics."],
  NVDA:["Customers range from hyperscalers to governments, spreading demand across buyers that need rapid deployment at scale.","Alternatives can compete on chips, but must also overcome NVIDIA's software, networking and developer ecosystem.","Continued workload growth would show developers are not meaningfully migrating away from CUDA.","Broader system sales indicate NVIDIA is capturing more of the cluster rather than only the accelerator.","Smooth transitions demonstrate that customers remain willing to adopt NVIDIA's rapid product cadence."],
  AVGO:["A small group of hyperscalers buys at enormous scale and values partners capable of multi-year custom design programs.","Rivals can contest individual programs, but replacing Broadcom requires comparable IP and co-design execution.","More programs would reduce dependence on any single customer and validate Broadcom's repeatability.","Rising content means Broadcom benefits as clusters require more connectivity per accelerator.","Repeat wins are the clearest evidence that customer knowledge and trust create durable switching costs."],
  ANET:["Large cloud operators demand exceptional reliability and automation because network failures idle costly infrastructure.","Cisco and NVIDIA have scale, but Arista's consistent software architecture remains its main point of differentiation.","Back-end wins would show EOS and Ethernet can extend successfully into the fastest-growing network segment.","Diversification would make the moat less dependent on a few hyperscaler relationships.","Retention through upgrades confirms that operational switching costs persist across hardware generations."],
  MSFT:["Enterprises and developers already operate inside Microsoft's identity, productivity and cloud environments.","Rivals may lead in individual categories, but few can match Microsoft's combined infrastructure and application distribution.","Paid expansion would demonstrate that distribution is converting into incremental revenue, not only bundled usage.","Growth alongside new supply shows Microsoft can turn heavy investment into utilised, differentiated capacity.","Cross-product use would prove the ecosystem is reinforcing itself and raising customer switching costs."],
  AMZN:["AWS serves organisations of every size, giving it diversified demand and a large base for new services.","Azure and Google Cloud are formidable, so breadth, execution and customer economics must keep differentiating AWS.","Sustained workload growth shows customers still prefer the platform despite credible alternatives.","Production adoption would validate custom silicon as a cost and supply advantage rather than a niche option.","Usage beyond compute suggests AWS is deepening its role and increasing customer dependence on the ecosystem."],
  GOOGL:["Its buyer base spans advertisers, consumers and enterprises, allowing AI investment to support several revenue engines.","Competition is broad, but Google's combination of data, distribution, models and infrastructure is unusually complete.","Rising engagement would show that built-in distribution is translating into habitual usage.","Customer and profit growth would prove Google can monetise its technical advantage in enterprise markets.","Stable usage and monetisation would show generative answers are strengthening rather than cannibalising Search."],
  META:["Users create attention and data, while advertisers fund the platform—two groups that reinforce each other.","Rivals compete for time and advertising budgets, but recreating Meta's social graphs and reach is difficult.","Engagement gains show AI is improving the core network rather than functioning as an isolated feature.","Better advertiser returns convert technical progress directly into pricing power and budget share.","External adoption would show Llama is becoming an ecosystem with influence beyond Meta's own products."],
  PLTR:["Customers operate in complex, regulated environments where governance and dependable deployment matter more than generic tools.","Internal builds and cloud platforms are alternatives, but often require more integration and implementation responsibility.","Expansion into production indicates the ontology is becoming embedded in real operating decisions.","Strong retention demonstrates that accumulated workflows and data relationships create genuine switching costs.","Faster repeatable delivery would show Palantir can scale its advantage without relying on bespoke consulting."],
  NOW:["Large organisations use ServiceNow across departments, giving new agents access to established workflows and permissions.","Competitors own adjacent systems, but replacing ServiceNow means rebuilding deeply configured cross-company processes.","Higher renewal value would prove AI increases platform economics rather than merely protecting existing contracts.","Consolidation shows customers prefer one governed workflow layer over a collection of disconnected tools.","Completed production actions demonstrate that agents are trusted to do work, not simply generate suggestions."],
  CRM:["Commercial teams work inside Salesforce daily, giving new AI products immediate access to users and customer context.","Competitors attack different parts of the stack, but Salesforce retains an unusually broad CRM data footprint.","Paid usage would show customers see enough measurable value to move beyond experimentation.","Broader adoption makes customer data more unified and strengthens the foundation for useful agents.","Stable retention would indicate AI is reinforcing the platform despite pressure on traditional seat-based software."]
};
for(const [ticker,context] of Object.entries(moatContext)) companies[ticker].moatContext=context;
const developmentUrls:Record<string,string>={
  VRT:"https://www.prnewswire.com/news-releases/vertiv-expands-global-manufacturing-capacity-for-ai-ready-data-center-cooling-solutions-302830933.html",GEV:"https://www.gevernova.com/news/press-releases/ge-vernova-to-acquire-robotech-automation",ETN:"https://www.eaton.com/us/en-us/company/news-insights/news-releases.html",ASML:"https://www.asml.com/en/news/press-releases",TSM:"https://pr.tsmc.com/english/news",CDNS:"https://www.cadence.com/en_US/home/company/newsroom.html",NVDA:"https://www.reuters.com/business/nvidia-buy-hugging-face-nearly-13-billion-big-bet-open-ai-models-2026-09-03/",AVGO:"https://investors.broadcom.com/news-releases",ANET:"https://investors.arista.com/news-and-events/news-releases",MSFT:"https://www.theverge.com/news/989102/microsoft-earnings-changes-azure-revenue",AMZN:"https://www.aboutamazon.com/news/aws",GOOGL:"https://blog.google/technology/ai/",META:"https://ai.meta.com/blog/",PLTR:"https://investors.palantir.com/news",NOW:"https://investor.servicenow.com/news/news-details/2026/ServiceNow-extends-agentic-AI-governance-from-desktops-to-data-centers-with-NVIDIA/default.aspx",CRM:"https://investor.salesforce.com/news/default.aspx"};
for(const [ticker,url] of Object.entries(developmentUrls)) companies[ticker].developmentUrl=url;
