type Seed={name:string;ticker:string;layer:string;moat:string;score:number;business:string;role:string;customers:string;competitors:string;edge:string;development:string;url:string};
const company=(themeLabel:string,themeHref:string,x:Seed)=>({
  ...x,developmentUrl:x.url,price:"—",move:"Analysis profile",metrics:[],themeLabel,themeHref,
  summary:`${x.name} occupies a difficult-to-replace position in ${x.layer.toLowerCase()}, supported by ${x.moat.toLowerCase()}.`,
  thesis:[x.edge,`Scale and accumulated expertise strengthen its position`,`Customer integration makes replacement costly or disruptive`],
  moatDurability:[`The core capability takes years and significant capital to reproduce`,`A larger installed base improves economics and customer relevance`,`Continued investment extends the advantage into adjacent needs`],
  signals:[`Share gains or expanding use within existing customers`,`Stable pricing and margins as competition increases`,`Evidence that new products deepen the customer relationship`],
  moatSignals:[`Share gains or expanding use within existing customers`,`Stable pricing and margins as competition increases`,`Evidence that new products deepen the customer relationship`],
  customerWhy:`These customers value reliability, integration and a proven ability to operate at scale.`,
  competitorWhy:`Alternatives exist, but matching the full combination of expertise, distribution and installed relationships is difficult.`,
  moatWhy:[`This is the scarce capability at the centre of the company’s competitive position.`,`Scale spreads fixed investment and produces operating knowledge smaller rivals cannot easily match.`,`Once embedded in a customer workflow, changing providers introduces cost, risk and retraining.`,`Recreating the asset base, approvals and specialist knowledge requires sustained investment.`,`More deployments create references, service revenue and data that reinforce future wins.`,`Adjacent products make the platform more useful and increase the cost of switching.`],
  moatContext:[`Demand is concentrated among buyers that cannot tolerate failure in this part of the system.`,`Competitors may match individual products, but rarely the same breadth, history and ecosystem.`,`This shows whether the moat is translating into greater customer preference.`,`Healthy economics indicate that differentiation is holding rather than being competed away.`,`Successful cross-selling suggests the advantage is widening beyond the original product.`]
});

const raw:Record<string,Seed>={
  BHP:{name:"BHP",ticker:"BHP",layer:"00 · Critical Materials",moat:"Tier-one resource base",score:87,business:"Produces copper, iron ore and other materials required for electrification and infrastructure.",role:"Its long-life assets supply materials that are difficult to add quickly when demand accelerates.",customers:"Smelters, manufacturers, utilities and industrial groups.",competitors:"Rio Tinto, Glencore and diversified miners.",edge:"Large, low-cost deposits support durable production economics",development:"BHP continues to prioritise copper as electrification raises long-term demand.",url:"https://www.bhp.com/news"},
  RIO:{name:"Rio Tinto",ticker:"RIO",layer:"00 · Critical Materials",moat:"Scale + scarce deposits",score:85,business:"Operates large mining and processing assets across iron ore, aluminium, copper and minerals.",role:"Its resource portfolio supplies the physical inputs behind grids, transport and clean generation.",customers:"Global metals processors, manufacturers and infrastructure builders.",competitors:"BHP, Vale and diversified miners.",edge:"Irreplaceable ore bodies and logistics networks create a cost advantage",development:"Rio Tinto is expanding copper exposure while protecting its low-cost asset base.",url:"https://www.riotinto.com/en/news"},
  CEG:{name:"Constellation Energy",ticker:"CEG",layer:"01 · Clean Generation",moat:"Nuclear fleet",score:88,business:"Operates the largest US nuclear fleet alongside other generation assets.",role:"Provides dependable, carbon-free electricity suited to round-the-clock industrial and data-centre demand.",customers:"Utilities, large enterprises, grid operators and wholesale power markets.",competitors:"Vistra, regulated utilities and new generation developers.",edge:"A licensed nuclear fleet is scarce, reliable and exceptionally slow to replicate",development:"Constellation is pursuing long-duration clean-power agreements with large electricity users.",url:"https://www.constellationenergy.com/newsroom.html"},
  PWR:{name:"Quanta Services",ticker:"PWR",layer:"02 · Grid Infrastructure",moat:"Specialist workforce",score:89,business:"Designs, builds and maintains electric transmission, distribution and energy infrastructure.",role:"Supplies the skilled labour and project execution required to expand and harden the grid.",customers:"Utilities, renewable developers, pipelines and communications providers.",competitors:"MYR Group, MasTec and local engineering contractors.",edge:"A scarce, safety-qualified workforce and national project capacity are hard to assemble",development:"Quanta continues to expand capacity for transmission, grid modernisation and large-load connections.",url:"https://investors.quantaservices.com/news-events/news-releases"},
  TSLA:{name:"Tesla",ticker:"TSLA",layer:"03 · Storage & Power Electronics",moat:"Integrated energy platform",score:80,business:"Builds electric vehicles, battery storage systems, charging products and energy software.",role:"Megapack combines battery supply, power electronics and software for grid-scale storage.",customers:"Utilities, power developers, businesses and vehicle owners.",competitors:"BYD, Fluence and global battery integrators.",edge:"Product integration and manufacturing scale shorten deployment and improve system performance",development:"Tesla is scaling dedicated Megapack production and its grid-services software.",url:"https://www.tesla.com/blog"},
  NEE:{name:"NextEra Energy",ticker:"NEE",layer:"03 · Storage & Power Electronics",moat:"Development scale",score:84,business:"Owns a regulated utility and one of the world’s largest renewable-energy development platforms.",role:"Combines capital, land, interconnection expertise and operating scale across clean generation and storage.",customers:"Utility customers, corporations and wholesale power buyers.",competitors:"AES, Brookfield Renewable and regional utilities.",edge:"A deep development pipeline and low-cost capital support repeatable project execution",development:"NextEra continues to develop renewables, storage and transmission for growing US power demand.",url:"https://www.nexteraenergy.com/news-and-events.html"},
  ABB:{name:"ABB",ticker:"ABB",layer:"04 · Electrification Platforms",moat:"Installed electrical base",score:86,business:"Provides electrification, motion, automation and robotics equipment globally.",role:"Its equipment controls and distributes electricity across factories, buildings and infrastructure.",customers:"Industrial companies, utilities, builders and data-centre operators.",competitors:"Schneider Electric, Siemens and Eaton.",edge:"A broad installed base connects mission-critical equipment to recurring service and upgrades",development:"ABB is investing in electrification capacity for data centres, industry and grid upgrades.",url:"https://global.abb/group/en/media"},
  SU:{name:"Schneider Electric",ticker:"SU",layer:"05 · Energy Management",moat:"Power + software integration",score:91,business:"Provides electrical distribution, automation and energy-management software.",role:"Connects physical power equipment with software that measures and optimises energy use.",customers:"Data centres, factories, buildings, utilities and infrastructure operators.",competitors:"Eaton, Siemens and ABB.",edge:"Deep integration between installed hardware and management software creates switching costs",development:"Schneider Electric continues to expand data-centre power, cooling and energy-management capacity.",url:"https://www.se.com/ww/en/about-us/newsroom/"},

  OKTA:{name:"Okta",ticker:"OKTA",layer:"00 · Identity & Access",moat:"Identity integration network",score:80,business:"Provides workforce and customer identity, authentication and access-management software.",role:"Acts as an independent control point between users, devices and applications.",customers:"Enterprises, developers and public-sector organisations.",competitors:"Microsoft, Ping Identity and CyberArk.",edge:"Thousands of integrations make a neutral identity layer more useful and difficult to replace",development:"Okta is extending identity controls for privileged access, governance and AI agents.",url:"https://www.okta.com/newsroom/"},
  CRWD:{name:"CrowdStrike",ticker:"CRWD",layer:"01 · Endpoint & Workload",moat:"Threat-data flywheel",score:91,business:"Runs a cloud-native security platform spanning endpoints, identity, cloud and operations.",role:"Its single agent collects telemetry and supports multiple security modules.",customers:"Enterprises, governments and managed security providers.",competitors:"Microsoft, Palo Alto Networks and SentinelOne.",edge:"Massive security telemetry improves detection while one platform lowers operational complexity",development:"CrowdStrike continues to consolidate more security modules on its Falcon platform.",url:"https://www.crowdstrike.com/en-us/press-releases/"},
  PANW:{name:"Palo Alto Networks",ticker:"PANW",layer:"02 · Network & Cloud Security",moat:"Security platform breadth",score:92,business:"Provides network, cloud and security-operations platforms.",role:"Unifies controls and telemetry across infrastructure that was historically protected by separate tools.",customers:"Large enterprises, governments and service providers.",competitors:"Fortinet, Cisco, CrowdStrike and cloud-native specialists.",edge:"Platform breadth and large-scale telemetry enable customers to consolidate vendors",development:"Palo Alto Networks is advancing its platformisation strategy across network, cloud and operations security.",url:"https://www.paloaltonetworks.com/company/press"},
  FTNT:{name:"Fortinet",ticker:"FTNT",layer:"02 · Network & Cloud Security",moat:"Custom security silicon",score:87,business:"Builds network-security appliances, software and secure networking products.",role:"Combines purpose-built processors with a broad security operating system.",customers:"Enterprises, service providers, governments and small businesses.",competitors:"Palo Alto Networks, Cisco and Check Point.",edge:"Custom chips deliver attractive price-performance across a broad appliance base",development:"Fortinet continues to integrate networking and security through its secure-access platform.",url:"https://www.fortinet.com/corporate/about-us/newsroom"},
  ZS:{name:"Zscaler",ticker:"ZS",layer:"03 · Zero Trust & Data",moat:"Cloud security network",score:87,business:"Operates a cloud-delivered zero-trust exchange for users, applications and data.",role:"Moves security policy from private network perimeters into a distributed cloud service.",customers:"Large enterprises and public-sector organisations.",competitors:"Palo Alto Networks, Netskope and traditional network vendors.",edge:"A large global inspection cloud improves performance, policy consistency and threat visibility",development:"Zscaler is extending zero-trust controls across data, workloads and AI usage.",url:"https://www.zscaler.com/press"},
  NET:{name:"Cloudflare",ticker:"NET",layer:"03 · Zero Trust & Data",moat:"Global edge network",score:88,business:"Operates a global network delivering security, performance and developer services.",role:"Inspects and accelerates traffic close to users while applying shared security intelligence.",customers:"Developers, internet businesses, enterprises and public-sector organisations.",competitors:"Akamai, hyperscalers and security-platform vendors.",edge:"A ubiquitous edge network supports many services on shared infrastructure",development:"Cloudflare continues to combine application security, zero trust and developer compute on one network.",url:"https://www.cloudflare.com/press/"},
  DDOG:{name:"Datadog",ticker:"DDOG",layer:"04 · Security Operations",moat:"Unified telemetry",score:84,business:"Provides cloud monitoring, observability and security software.",role:"Combines infrastructure, application and security signals so teams can investigate problems in context.",customers:"Software companies and enterprises operating cloud applications.",competitors:"Dynatrace, Splunk, New Relic and cloud-native tools.",edge:"A shared data platform makes additional monitoring and security modules more valuable",development:"Datadog is broadening security and AI observability across its integrated telemetry platform.",url:"https://www.datadoghq.com/about/latest-news/"},
  CYBR:{name:"CyberArk",ticker:"CYBR",layer:"05 · Privileged Security",moat:"Privileged-access standard",score:88,business:"Secures privileged accounts, workforce identities and machine credentials.",role:"Protects the high-value credentials attackers target to move through organisations.",customers:"Large enterprises, governments and regulated industries.",competitors:"Okta, Microsoft and BeyondTrust.",edge:"Deep workflows around privileged access make the platform highly embedded",development:"CyberArk is expanding from privileged access into a broader identity-security platform.",url:"https://www.cyberark.com/press/"},

  ROK:{name:"Rockwell Automation",ticker:"ROK",layer:"00 · Controls & Motion",moat:"Factory control standard",score:85,business:"Provides industrial control systems, automation software and lifecycle services.",role:"Its controllers and software coordinate machinery across mission-critical production lines.",customers:"Manufacturers, logistics operators and industrial integrators.",competitors:"Siemens, Schneider Electric and Mitsubishi Electric.",edge:"Long-lived control architectures and engineering familiarity create high switching costs",development:"Rockwell is embedding analytics, autonomy and digital design deeper into industrial automation.",url:"https://www.rockwellautomation.com/en-us/company/news.html"},
  KEY:{name:"Keyence",ticker:"KEY",layer:"01 · Sensors & Machine Vision",moat:"Direct-sales expertise",score:93,business:"Develops sensors, machine-vision systems, measurement tools and automation components.",role:"Gives machines the precision sensing needed to inspect, measure and respond.",customers:"Factories, machine builders and automation engineers.",competitors:"Cognex, Omron and specialised sensor vendors.",edge:"A high-touch sales engineering model turns a broad product catalogue into tailored solutions",development:"Keyence continues to introduce higher-precision sensing and inspection products for automated factories.",url:"https://www.keyence.com/about-us/news/"},
  CGNX:{name:"Cognex",ticker:"CGNX",layer:"01 · Sensors & Machine Vision",moat:"Machine-vision expertise",score:84,business:"Builds machine-vision systems and industrial barcode readers.",role:"Enables automated equipment to inspect quality, identify objects and guide motion.",customers:"Manufacturers, logistics operators and automation integrators.",competitors:"Keyence, Omron and emerging vision-software providers.",edge:"A large library of vision algorithms and applications expertise improves deployment success",development:"Cognex is adding AI-based vision tools that simplify difficult industrial inspection tasks.",url:"https://www.cognex.com/company/press-releases"},
  FANUY:{name:"Fanuc",ticker:"FANUY",layer:"02 · Industrial Robots",moat:"Installed robot base",score:89,business:"Manufactures industrial robots, CNC systems and factory-automation equipment.",role:"Supplies reliable motion platforms used across automotive and general manufacturing.",customers:"Automakers, industrial manufacturers and system integrators.",competitors:"ABB, Yaskawa and Kuka.",edge:"Reliability, service infrastructure and a vast installed base support repeat purchases",development:"Fanuc continues to develop collaborative and easier-to-program robots for wider industrial use.",url:"https://www.fanuc.co.jp/en/profile/ir/index.html"},
  SYM:{name:"Symbotic",ticker:"SYM",layer:"03 · Warehouse Automation",moat:"Integrated warehouse system",score:78,business:"Builds AI-enabled robotics systems for high-volume warehouse operations.",role:"Combines robots, storage architecture and orchestration software into one automated system.",customers:"Large retailers, wholesalers and grocery distributors.",competitors:"AutoStore, Ocado and warehouse-automation integrators.",edge:"Full-system integration and operational learning improve throughput at large scale",development:"Symbotic is scaling deployments while expanding its automation platform to additional warehouse formats.",url:"https://www.symbotic.com/news-events/news/"},
  DE:{name:"Deere & Company",ticker:"DE",layer:"04 · Autonomous Machines",moat:"Fleet + agronomic data",score:90,business:"Builds agricultural, construction and forestry equipment with precision technology.",role:"Integrates autonomy, perception and software into machines already trusted by farmers.",customers:"Farmers, contractors, dealers and governments.",competitors:"CNH Industrial, AGCO and specialised autonomy startups.",edge:"A large connected fleet, dealer network and agronomic data create a powerful deployment advantage",development:"Deere continues to roll out autonomous and precision capabilities across more farm operations.",url:"https://www.deere.com/en/news/"},
  ISRG:{name:"Intuitive Surgical",ticker:"ISRG",layer:"05 · Specialised Robotics",moat:"Procedure ecosystem",score:96,business:"Develops da Vinci robotic surgical systems, instruments and services.",role:"Combines installed systems, trained surgeons and procedure-specific instruments into a recurring ecosystem.",customers:"Hospitals, surgeons and health systems.",competitors:"Medtronic, Johnson & Johnson and specialised surgical-robotics firms.",edge:"Clinical training, evidence and a huge installed base reinforce recurring instrument usage",development:"Intuitive Surgical is expanding adoption of its newest da Vinci platform and supported procedures.",url:"https://isrg.intuitive.com/news-releases"},

  RKLB:{name:"Rocket Lab",ticker:"RKLB",layer:"00 · Launch & Propulsion",moat:"Integrated space systems",score:79,business:"Provides launch services, spacecraft, satellite components and mission operations.",role:"Combines access to orbit with a growing set of systems used to build and operate spacecraft.",customers:"Governments, defence agencies and commercial satellite operators.",competitors:"SpaceX, Firefly and traditional aerospace primes.",edge:"Flight heritage plus vertical integration supports faster, lower-risk missions",development:"Rocket Lab is developing Neutron while broadening its spacecraft and defence-systems portfolio.",url:"https://www.rocketlabusa.com/updates/"},
  NOC:{name:"Northrop Grumman",ticker:"NOC",layer:"01 · Spacecraft & Payloads",moat:"Mission heritage",score:90,business:"Builds defence systems, satellites, payloads and strategic space infrastructure.",role:"Supplies high-consequence spacecraft and sensors where reliability and security dominate cost.",customers:"US and allied governments, intelligence agencies and prime contractors.",competitors:"Lockheed Martin, Boeing and emerging space suppliers.",edge:"Decades of classified-program experience and proven missions create formidable trust barriers",development:"Northrop Grumman continues to deliver national-security spacecraft and resilient space architectures.",url:"https://news.northropgrumman.com/"},
  LHX:{name:"L3Harris Technologies",ticker:"LHX",layer:"01 · Spacecraft & Payloads",moat:"Trusted mission systems",score:86,business:"Provides sensors, communications, propulsion and mission systems for defence and space.",role:"Its specialised components connect spacecraft, ground networks and national-security missions.",customers:"US and allied defence agencies, NASA and aerospace primes.",competitors:"RTX, Northrop Grumman and specialist component suppliers.",edge:"Security clearances and long programme histories make trusted systems hard to displace",development:"L3Harris is integrating space sensing, communications and propulsion across larger defence programmes.",url:"https://www.l3harris.com/newsroom"},
  PL:{name:"Planet Labs",ticker:"PL",layer:"02 · Earth Observation",moat:"Daily imagery archive",score:77,business:"Operates a large fleet of Earth-imaging satellites and sells geospatial data subscriptions.",role:"Turns frequent global imagery into a longitudinal dataset for monitoring change.",customers:"Governments, agriculture, mapping, finance and sustainability teams.",competitors:"Maxar, BlackSky and public satellite programmes.",edge:"Daily revisit frequency and a growing historical archive make the dataset more useful over time",development:"Planet is adding higher-resolution sensors and AI-ready data products to its daily monitoring platform.",url:"https://www.planet.com/pulse/"},
  BKSY:{name:"BlackSky Technology",ticker:"BKSY",layer:"02 · Earth Observation",moat:"Rapid revisit intelligence",score:74,business:"Provides high-frequency satellite imagery and AI-enabled geospatial intelligence.",role:"Combines taskable satellites with analytics for time-sensitive monitoring.",customers:"Defence, intelligence and commercial organisations.",competitors:"Planet, Maxar and government-owned systems.",edge:"Fast collection-to-insight workflows matter for customers making urgent decisions",development:"BlackSky continues to expand its next-generation constellation and real-time intelligence capabilities.",url:"https://www.blacksky.com/news/"},
  IRDM:{name:"Iridium Communications",ticker:"IRDM",layer:"03 · Space Communications",moat:"Global L-band constellation",score:91,business:"Operates a global satellite network for voice, data and safety communications.",role:"Provides dependable connectivity across oceans, poles and remote areas beyond terrestrial networks.",customers:"Governments, maritime, aviation, industrial and personal communications users.",competitors:"Globalstar, Inmarsat/Viasat and newer broadband constellations.",edge:"Truly global coverage, regulated spectrum and safety certifications are extremely difficult to duplicate",development:"Iridium is expanding direct-to-device and standards-based services on its established constellation.",url:"https://investor.iridium.com/news-releases"},
  GSAT:{name:"Globalstar",ticker:"GSAT",layer:"03 · Space Communications",moat:"Licensed spectrum + constellation",score:75,business:"Provides satellite connectivity and terrestrial spectrum services.",role:"Its spectrum and satellite assets support low-bandwidth connectivity and direct-to-device services.",customers:"Device platforms, enterprises, governments and remote users.",competitors:"Iridium, terrestrial carriers and emerging satellite networks.",edge:"Globally coordinated spectrum and an operating network create scarce strategic assets",development:"Globalstar is investing in next-generation satellites and expanded direct-to-device capacity.",url:"https://investors.globalstar.com/news-releases"},
  VSAT:{name:"Viasat",ticker:"VSAT",layer:"04 · Ground & Data Infrastructure",moat:"Integrated satellite network",score:78,business:"Provides satellite broadband, mobility connectivity and secure government communications.",role:"Connects space assets to aircraft, ships, governments and ground infrastructure.",customers:"Airlines, maritime operators, governments, enterprises and consumers.",competitors:"Starlink, SES and terrestrial communications providers.",edge:"Orbital assets, spectrum and specialised mobility distribution create a broad service platform",development:"Viasat is integrating global satellite capacity to improve aviation, maritime and government services.",url:"https://news.viasat.com/"},
  LMT:{name:"Lockheed Martin",ticker:"LMT",layer:"05 · Defence Space Platforms",moat:"Classified programme access",score:92,business:"Builds defence platforms, satellites, missile-warning systems and national-security technology.",role:"Acts as a prime integrator for complex, long-duration government space programmes.",customers:"US and allied governments and security agencies.",competitors:"Northrop Grumman, Boeing and emerging defence-technology firms.",edge:"Trusted access, programme knowledge and systems integration are reinforced across decades",development:"Lockheed Martin continues to develop resilient missile-warning, communications and national-security space systems.",url:"https://news.lockheedmartin.com/"},
};

const layers=(items:any[])=>items.map((x,i)=>({n:String(i).padStart(2,"0"),...x}));
export const themes:Record<string,any>={
 "energy-transition":{title:"Energy Transition",number:"03",overline:"ELECTRIFICATION & INFRASTRUCTURE",top:"ENERGY USE & OPTIMISATION",bottom:"PHYSICAL RESOURCES",icon:"⚡",intro:"Six connected layers turn scarce materials into dependable, controllable electricity for a more electrified economy.",coreIdea:"Electricity demand is accelerating faster than mines, generation and grid capacity can be built—making physical bottlenecks increasingly valuable.",layers:layers([
  {title:"Critical Materials",short:"Materials",color:"#d6ff5f",thesis:"Electrification begins with copper, aluminium and other constrained physical inputs.",explainer:"Mines and processing assets take years to permit and build. Deposit quality, location and infrastructure determine which producers can supply growing demand at attractive costs.",value:"Low-cost, long-life deposits capture value when supply is slow to respond.",risk:"Substitution, recycling, project overruns and commodity cycles can weaken returns.",includes:["Copper","Aluminium","Minerals"],signals:["Mine supply additions remain difficult","Grid investment lifts copper intensity"],companies:["BHP","RIO"]},
  {title:"Clean & Firm Generation",short:"Generation",color:"#78e7ff",thesis:"More electricity demand requires dependable generation, not capacity in name alone.",explainer:"Nuclear, gas, hydro and renewables play different roles. The scarcest assets can deliver reliable power at the location and hour customers actually need it.",value:"Licensed sites, existing interconnections and reliable output command a premium.",risk:"Power prices, regulation and construction costs can reshape project economics.",includes:["Nuclear","Renewables","Firm power"],signals:["Large users sign long contracts","Capacity markets reward reliability"],companies:["CEG","NEE"]},
  {title:"Grid Infrastructure",short:"Grid",color:"#a894ff",thesis:"Generation has little value if power cannot reach the customer.",explainer:"Transmission, substations and distribution equipment form the bottleneck between new supply and new loads. Skilled crews and permitted rights-of-way are as important as hardware.",value:"Backlogs and scarce engineering capacity support pricing and visibility.",risk:"Permitting delays, utility budgets and labour constraints slow conversion.",includes:["Transmission","Substations","Distribution"],signals:["Interconnection queues stay long","Utility capital plans rise"],companies:["PWR","SU"]},
  {title:"Storage & Power Electronics",short:"Storage",color:"#ffb86b",thesis:"Storage shifts electricity through time while power electronics keep the system stable.",explainer:"Batteries, inverters and control systems balance variable generation and fast-growing loads. Integration and bankable performance matter more than commodity cells alone.",value:"Validated systems and software-led integration earn the strongest returns.",risk:"Cell oversupply, safety failures and technology change can compress margins.",includes:["Batteries","Inverters","Controls"],signals:["Storage duration and deployments grow","Grid services add revenue streams"],companies:["TSLA","NEE"]},
  {title:"Electrification Platforms",short:"Equipment",color:"#ff7ab6",thesis:"Every new electrical load requires safe distribution, switching and control.",explainer:"Factories, buildings and data centres depend on mission-critical equipment qualified over long operating lives. Installed products seed service, replacement and expansion demand.",value:"Broad portfolios and installed bases create recurring, specification-led demand.",risk:"Industrial cycles and component shortages can interrupt growth.",includes:["Switchgear","Automation","Motors"],signals:["Electrical backlogs stay elevated","Customers standardise on platforms"],companies:["ABB","SU"]},
  {title:"Energy Management",short:"Software",color:"#6fffc5",thesis:"The highest layer measures, orchestrates and reduces the cost of electricity use.",explainer:"Software makes distributed equipment visible and controllable. The strongest systems connect directly to installed hardware and sit inside daily operating decisions.",value:"Recurring software and service revenue deepen hardware relationships.",risk:"Open standards and standalone software can reduce platform control.",includes:["Monitoring","Optimisation","Demand response"],signals:["Software attaches to equipment sales","Efficiency becomes a board priority"],companies:["SU","ABB"]}
 ])},
 "cybersecurity":{title:"Cybersecurity",number:"04",overline:"TRUST & DIGITAL DEFENCE",top:"GOVERNANCE & RESPONSE",bottom:"IDENTITY & ACCESS",icon:"◈",intro:"Six connected layers decide who and what can be trusted, protect digital activity and help organisations recover when controls fail.",coreIdea:"As digital complexity grows, value shifts to platforms that control identity, unify security data and become the trusted point of enforcement.",layers:layers([
  {title:"Identity & Access",short:"Identity",color:"#d6ff5f",thesis:"Security starts by verifying every human and machine requesting access.",explainer:"Identity systems authenticate users, enforce privileges and remove access as roles change. They become critical infrastructure because every application depends on the same trust decisions.",value:"Deep integrations and a central policy role create durable switching costs.",risk:"Platform bundling and security failures can undermine independence and trust.",includes:["Authentication","SSO","Governance"],signals:["Machine identities grow rapidly","Privilege controls converge"],companies:["OKTA","CYBR"]},
  {title:"Endpoint & Workload",short:"Endpoint",color:"#78e7ff",thesis:"Endpoints and workloads are where code executes—and where many attacks begin.",explainer:"Lightweight agents observe behaviour, prevent malicious activity and collect telemetry. Cloud delivery lets vendors improve protection across the full customer base at once.",value:"High-quality telemetry and multi-module platforms capture the most value.",risk:"Outages, agent complexity and bundled alternatives can trigger consolidation.",includes:["Devices","Servers","Workloads"],signals:["Customers adopt more modules","Threat telemetry expands"],companies:["CRWD","PANW"]},
  {title:"Network & Cloud Security",short:"Network",color:"#a894ff",thesis:"Traffic must be inspected wherever users, applications and data meet.",explainer:"Modern controls span branches, clouds and remote users rather than a single perimeter. Policy consistency and performance at global scale are decisive.",value:"Shared platforms displace fragmented appliances and point products.",risk:"Hyperscalers and intense competition can commoditise individual controls.",includes:["Firewalls","SASE","Cloud posture"],signals:["Security and networking converge","Platform contracts grow"],companies:["PANW","FTNT"]},
  {title:"Zero Trust & Data",short:"Data",color:"#ffb86b",thesis:"Access should be continuously verified and limited to the exact resource required.",explainer:"Zero-trust services broker connections without exposing entire networks. Data controls add context about what information is sensitive and how it may move.",value:"Policy enforcement close to users and data creates a strategic control point.",risk:"Complex deployments and overlapping platforms can slow adoption.",includes:["Zero trust","DLP","Edge security"],signals:["Private access replaces VPNs","AI data controls gain urgency"],companies:["ZS","NET"]},
  {title:"Security Operations",short:"Operations",color:"#ff7ab6",thesis:"Security teams need one operating picture across enormous volumes of alerts.",explainer:"Operations platforms correlate telemetry, automate investigations and help responders act quickly. Better context reduces false positives and scarce analyst time.",value:"Unified data and workflow automation expand revenue per customer.",risk:"AI could lower differentiation if underlying data remains fragmented.",includes:["SIEM","Observability","Automation"],signals:["Investigation time falls","Telemetry consolidates"],companies:["CRWD","DDOG"]},
  {title:"Governance & Resilience",short:"Governance",color:"#6fffc5",thesis:"Boards ultimately care whether the organisation can control risk and recover.",explainer:"Governance connects technical controls to regulation, insurance and business continuity. Resilience depends on tested identity, data and response processes across the stack.",value:"Platforms tied to audit and operating processes become embedded.",risk:"Compliance tools without technical depth can become checklist software.",includes:["Compliance","Recovery","Risk"],signals:["Cyber risk reaches boards","Rules demand evidence"],companies:["CYBR","PANW"]}
 ])},
 "robotics":{title:"Robotics",number:"05",overline:"AUTOMATION & PHYSICAL AI",top:"AUTONOMOUS SYSTEMS",bottom:"CONTROL & SENSING",icon:"⌁",intro:"Six connected layers turn precise components, perception and software into machines that can act safely in the physical world.",coreIdea:"The strongest robotics moats form around complete workflows—combining reliable hardware, domain data, software and long-lived customer integration.",layers:layers([
  {title:"Controls & Motion",short:"Control",color:"#d6ff5f",thesis:"Every robot begins with reliable control of motors, drives and machinery.",explainer:"Industrial controllers translate software commands into precise physical action. Qualification, uptime and compatibility keep established platforms embedded for decades.",value:"Installed standards create replacement, service and expansion demand.",risk:"Industrial cycles and open architectures can weaken proprietary control.",includes:["PLC","Drives","Motion"],signals:["Automation capital spending rises","Installed bases migrate gradually"],companies:["ROK","ABB"]},
  {title:"Sensors & Machine Vision",short:"Perception",color:"#78e7ff",thesis:"Machines need dependable perception before they can act autonomously.",explainer:"Vision, measurement and safety sensors convert the physical environment into useful data. Applications expertise is essential because factory conditions vary widely.",value:"High-precision products and direct engineering support sustain premium margins.",risk:"Cheaper cameras and general AI models can erode hardware differentiation.",includes:["Vision","Measurement","Safety"],signals:["AI inspection adoption grows","Precision requirements rise"],companies:["KEY","CGNX"]},
  {title:"Industrial Robots",short:"Robots",color:"#a894ff",thesis:"Robot arms provide repeatable motion for high-volume manufacturing.",explainer:"Hardware reliability, controls, service and integrator familiarity determine lifetime economics. The installed base matters because factories standardise training and spares.",value:"Service networks and ecosystems reinforce hardware sales.",risk:"Cyclical orders and price competition from new entrants pressure returns.",includes:["Robot arms","Cobots","CNC"],signals:["Robot density increases","Cobots broaden use cases"],companies:["FANUY","ABB"]},
  {title:"Warehouse Automation",short:"Logistics",color:"#ffb86b",thesis:"Warehouses reward complete systems that improve flow, not isolated robots.",explainer:"Storage architecture, mobile robots and orchestration software must work together around the clock. Deployment learning and uptime become part of the product.",value:"Integrated systems create long contracts and expansion opportunities.",risk:"Project execution and customer concentration can make growth uneven.",includes:["Fulfilment","Sorting","Orchestration"],signals:["Labour scarcity persists","Throughput improves at scale"],companies:["SYM","ROK"]},
  {title:"Autonomous Machines",short:"Autonomy",color:"#ff7ab6",thesis:"Autonomy combines perception, planning and control inside a real machine.",explainer:"Farms, mines and construction sites offer structured, high-value environments where automation can solve labour and productivity constraints sooner than general-purpose robots.",value:"Existing fleets and domain data provide privileged distribution.",risk:"Safety, regulation and edge cases extend deployment timelines.",includes:["Agriculture","Construction","Mobility"],signals:["Paid autonomy reaches fleets","Human supervision falls"],companies:["DE","TSLA"]},
  {title:"Specialised Robotics",short:"Specialists",color:"#6fffc5",thesis:"The strongest robots often dominate one costly, tightly defined workflow.",explainer:"Healthcare and other specialist markets reward systems backed by training, evidence and consumables. The moat grows around the full procedure rather than the machine alone.",value:"Installed systems generate recurring instruments, software and service revenue.",risk:"Procedure growth, reimbursement and competing clinical evidence matter.",includes:["Surgery","Healthcare","Field systems"],signals:["Procedures per system rise","New use cases win approval"],companies:["ISRG","DE"]}
 ])},
 "space-economy":{title:"Space Economy",number:"06",overline:"ORBITAL INFRASTRUCTURE",top:"SERVICES & MISSIONS",bottom:"ACCESS TO ORBIT",icon:"◎",intro:"Six connected layers move hardware into orbit, collect and transmit data, and turn space infrastructure into dependable services on Earth.",coreIdea:"Durable advantage comes from assets that cannot be recreated quickly: flight heritage, spectrum, orbital networks and trusted mission integration.",layers:layers([
  {title:"Launch & Propulsion",short:"Launch",color:"#d6ff5f",thesis:"All orbital activity begins with reliable, affordable access to space.",explainer:"Launch economics depend on cadence, vehicle reliability and manufacturing learning. Integrated providers can capture more of the mission beyond the rocket itself.",value:"Flight heritage and reusable or repeatable operations create cost advantages.",risk:"Failures, delays and dominant competitors can reset customer confidence.",includes:["Rockets","Engines","Launch sites"],signals:["Cadence rises","Backlogs diversify"],companies:["RKLB","NOC"]},
  {title:"Spacecraft & Payloads",short:"Spacecraft",color:"#78e7ff",thesis:"Satellites are specialised systems built to survive and perform without repair.",explainer:"Buses, sensors, power and propulsion must meet extreme mission requirements. Heritage and security clearance matter because failure costs dwarf component savings.",value:"Trusted suppliers win repeat positions on long-duration programmes.",risk:"Programme concentration and fixed-price execution can destroy economics.",includes:["Satellite buses","Sensors","Payloads"],signals:["Proliferated constellations grow","Payload demand broadens"],companies:["NOC","LHX"]},
  {title:"Earth Observation",short:"Observation",color:"#a894ff",thesis:"Repeated imagery turns physical change into a continuously updated dataset.",explainer:"Value increases with revisit frequency, resolution, archive depth and analytics. Customers pay for decisions, so fast delivery and workflow integration matter as much as pixels.",value:"Proprietary archives and mission workflows support recurring subscriptions.",risk:"Public data, falling launch costs and imagery oversupply can pressure pricing.",includes:["Imagery","Analytics","Geospatial data"],signals:["Government contracts recur","AI expands use cases"],companies:["PL","BKSY"]},
  {title:"Space Communications",short:"Networks",color:"#ffb86b",thesis:"Satellite networks connect places and devices beyond terrestrial coverage.",explainer:"Constellations combine spectrum, satellites, gateways and certified devices. Coverage and reliability improve only when the complete network is deployed and operated well.",value:"Scarce spectrum and established distribution reinforce network economics.",risk:"Capital intensity and new constellations can trigger prolonged price competition.",includes:["L-band","Direct-to-device","IoT"],signals:["Devices connect directly","Service revenue compounds"],companies:["IRDM","GSAT"]},
  {title:"Ground & Data Infrastructure",short:"Ground",color:"#ff7ab6",thesis:"Orbital assets need ground networks, terminals and software to become useful.",explainer:"Gateways route traffic, terminals reach users and software schedules complex fleets. Integration determines the quality customers experience on Earth.",value:"Installed terminals and managed networks support recurring service revenue.",risk:"Technology transitions and capacity price declines can strand older assets.",includes:["Gateways","Terminals","Mission software"],signals:["Mobility demand rises","Networks interoperate"],companies:["VSAT","LHX"]},
  {title:"Defence Space Platforms",short:"Defence",color:"#6fffc5",thesis:"National security funds the most demanding and resilient space systems.",explainer:"Prime contractors integrate sensors, spacecraft, communications and ground control under strict security requirements. Trust compounds across multi-decade programmes.",value:"Clearances, mission heritage and integration capability limit credible bidders.",risk:"Budget shifts, procurement delays and programme overruns can dominate results.",includes:["Missile warning","Secure comms","Space domain awareness"],signals:["Resilience budgets expand","Architectures proliferate"],companies:["LMT","NOC"]}
 ])}
};

const owners:Record<string,[string,string]>= {"energy-transition":["Energy Transition","/thesis/energy-transition"],cybersecurity:["Cybersecurity","/thesis/cybersecurity"],robotics:["Robotics","/thesis/robotics"],"space-economy":["Space Economy","/thesis/space-economy"]};
export const themeCompanies:Record<string,any>={};
for(const [slug,t] of Object.entries(themes)) for(const l of t.layers) for(const ticker of l.companies) if(raw[ticker]&&!themeCompanies[ticker]) themeCompanies[ticker]=company(owners[slug][0],owners[slug][1],raw[ticker]);
